In [3]:
from pathlib import Path
import pandas as pd

In [8]:
dir = Path().cwd().joinpath("corpcodeinfo.csv")
df = pd.read_csv(dir)

In [10]:
df.dropna(subset=['stock_code'])

,Unnamed: 0,corp_code,corp_name,corp_eng_name,stock_code,modify_date
0,0,434003,다코,Daco corporation,,20170630
1,1,430964,굿앤엘에스,"Good & LS Co.,Ltd.",,20170630
2,2,388953,크레디피아제이십오차유동화전문회사,Credipia 25th Asset Securitization Specialty L...,,20170630
3,3,179984,연방건설산업,youn bao,,20170630
4,4,420143,브룩스피알아이오토메이션잉크,"BROOKS-PRI Automation, Inc.",,20170630
...,...,...,...,...,...,...
113052,113052,1913987,지엠에프십사호선박투자회사,GMF NO.14 Ship Investment Company,,20250423
113053,113053,1913996,지엠에프십오호선박투자회사,GMF NO.15 Ship Investment Company,,20250423
113054,113054,1914001,지엠에프십육호선박투자회사,GMF NO.16 Ship Investment Company,,20250423
113055,113055,1913127,디지탈테크,"digitalltek co.,ltd.",,20250423
113056,113056,1913491,피유란,"PYURAN Co., Ltd.",,20250423

In [21]:
df[~df.stock_code.replace({" ": pd.NaT}).isna()]

,Unnamed: 0,corp_code,corp_name,corp_eng_name,stock_code,modify_date
1945,1945,260985,한빛네트,"HanbitNet, Inc.",036720,20170630
1957,1957,264529,엔플렉스,"Nplex,Inc.",040130,20170630
1958,1958,358545,동서정보기술,"Dong Seo Information Technology Co., Ltd.",055000,20170630
2698,2698,231567,애드모바일,,032600,20170630
3770,3770,359614,리더컴,"LEADER COMM.Co.,Ltd",056140,20170630
...,...,...,...,...,...,...
113021,113021,1626391,오가노이드사이언스,ORGANOIDSCIENCES LTD.,476040,20250509
113026,113026,136776,제이준코스메틱,"Jayjun Cosmetic Co., Ltd.",025620,20250808
113027,113027,1227039,브릿지바이오,"BRIDGE BIOTHERAPEUTICS, INC.",288330,20250808
113032,113032,532855,한국유니온제약,"UNION KOREA PHARM CO.,Ltd",080720,20250630
113041,113041,307189,에스케이엔펄스,"SK enpulse Co., Ltd",057500,20250627