In [1]:
%cd "C:/Users/ajcltm/vscode/data/250811_ecoDataSystem"

C:\Users\ajcltm\vscode\data\250811_ecoDataSystem

C:\Users\ajcltm\vscode\data\250811_ecoDataSystem\.venv\lib\site-packages\IPython\core\magics\osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

In [5]:
from etl.extract.extracter_fnltt import Extracter_fnltt

In [6]:
ex_fnltt = Extracter_fnltt()

In [7]:
ex_fnltt.extract("00260985")

Error: 조회된 데이타가 없습니다.

In [3]:
from etl.extract.extracter_stockcorpfnltt import Extracter_stockcorpfnltt

In [5]:
ex_s = Extracter_stockcorpfnltt()
ex_s.extract()

Target corporation codes: ['00434003', '00430964', '00388953', '00179984', '00420143', '00401111', '00435534', '00430186', '00430201', '00430210']...

,corp_code,fs_div,유동자산,비유동자산,자산총계,유동부채,비유동부채,부채총계,자본금,이익잉여금,자본총계,매출액,영업이익,법인세차감전 순이익,당기순이익,당기순이익(손실),총포괄손익
0,00126380,CFS,"195,936,557,000,000","259,969,423,000,000","455,905,980,000,000","75,719,452,000,000","16,508,663,000,000","92,228,115,000,000","897,514,000,000","346,652,238,000,000","363,677,865,000,000","258,935,494,000,000","6,566,976,000,000","11,006,265,000,000","15,487,100,000,000","15,487,100,000,000","18,837,411,000,000"
1,00164742,CFS,"101,724,717,000,000","180,738,638,000,000","282,463,355,000,000","73,362,103,000,000","107,291,812,000,000","180,653,915,000,000","1,488,993,000,000","88,665,805,000,000","101,809,440,000,000","162,663,579,000,000","15,126,901,000,000","17,618,662,000,000","12,272,301,000,000","12,272,301,000,000","12,428,841,000,000"
2,00113526,CFS,"8,595,169,639,226","21,796,606,390,430","30,391,776,029,656","9,409,864,309,283","11,166,703,478,740","20,576,567,788,023","1,846,657,275,000","2,591,941,106,956","9,815,208,241,633","16,111,796,106,147","1,790,089,190,805","1,575,690,364,023","1,129,105,735,756","1,129,105,735,756","865,564,479,919"

In [4]:
ex_s = Extracter_stockcorpfnltt()
target = ex_s.get_target_corpcode()
len(target)

3888

In [10]:
from repository.repository_corpcodeinfo import Repository_corpcodeinfo

corpcodeinfo = Repository_corpcodeinfo().select_all()

In [11]:
corpcodeinfo

,corp_code,corp_name,corp_eng_name,stock_code,modify_date
0,00434003,다코,Daco corporation,,20170630
1,00430964,굿앤엘에스,"Good & LS Co.,Ltd.",,20170630
2,00388953,크레디피아제이십오차유동화전문회사,Credipia 25th Asset Securitization Specialty L...,,20170630
3,00179984,연방건설산업,youn bao,,20170630
4,00420143,브룩스피알아이오토메이션잉크,"BROOKS-PRI Automation, Inc.",,20170630
...,...,...,...,...,...
113097,01913987,지엠에프십사호선박투자회사,GMF NO.14 Ship Investment Company,,20250423
113098,01913996,지엠에프십오호선박투자회사,GMF NO.15 Ship Investment Company,,20250423
113099,01914001,지엠에프십육호선박투자회사,GMF NO.16 Ship Investment Company,,20250423
113100,01913127,디지탈테크,"digitalltek co.,ltd.",,20250423
113101,01913491,피유란,"PYURAN Co., Ltd.",,20250423

In [12]:
corpcodeinfo[corpcodeinfo["corp_code"] == "00260985"]

     corp_code corp_name    corp_eng_name stock_code  modify_date
1945  00260985      한빛네트  HanbitNet, Inc.     036720     20170630

In [23]:
import pandas as pd
corpcodeinfo['stock_code'].replace({" " :pd.NA}, inplace=True)
corpcodeinfo['stock_code']==" "

C:\Users\ajcltm\AppData\Local\Temp\ipykernel_11948\2749476138.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  corpcodeinfo['stock_code'].replace({" " :pd.NA}, inplace=True)

0         False
1         False
2         False
3         False
4         False
          ...
113097    False
113098    False
113099    False
113100    False
113101    False
Name: stock_code, Length: 113102, dtype: bool

In [18]:
corpcodeinfo[corpcodeinfo["stock_code"].notnull()]

,Unnamed: 0,corp_code,corp_name,corp_eng_name,stock_code,modify_date
0,0,00434003,다코,Daco corporation,,20170630
1,1,00430964,굿앤엘에스,"Good & LS Co.,Ltd.",,20170630
2,2,00388953,크레디피아제이십오차유동화전문회사,Credipia 25th Asset Securitization Specialty L...,,20170630
3,3,00179984,연방건설산업,youn bao,,20170630
4,4,00420143,브룩스피알아이오토메이션잉크,"BROOKS-PRI Automation, Inc.",,20170630
...,...,...,...,...,...,...
113097,113097,01913987,지엠에프십사호선박투자회사,GMF NO.14 Ship Investment Company,,20250423
113098,113098,01913996,지엠에프십오호선박투자회사,GMF NO.15 Ship Investment Company,,20250423
113099,113099,01914001,지엠에프십육호선박투자회사,GMF NO.16 Ship Investment Company,,20250423
113100,113100,01913127,디지탈테크,"digitalltek co.,ltd.",,20250423
113101,113101,01913491,피유란,"PYURAN Co., Ltd.",,20250423